In [1]:
import numpy as np

In [7]:
A = np.array([[1,1,0], [0,0,1], [1,0,0]])
A

array([[1, 1, 0],
       [0, 0, 1],
       [1, 0, 0]])

In [11]:
A2 = A@A

A2

array([[1, 1, 1],
       [1, 0, 0],
       [1, 1, 0]])

In [13]:
A3 = A@A2
A3

array([[2, 1, 1],
       [1, 1, 0],
       [1, 1, 1]])

In [14]:
A = np.array([
    [0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
	[1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
	[1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
	[0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
	[1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
	[0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
	[0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
	[0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
])

In [15]:
np.trace(A)

0

In [16]:
A == A.T

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

26

In [24]:
def is_connected(adj_matrix):
    # initialize visited list and stack
    visited = [False] * len(adj_matrix)
    stack = []

    # push the first vertex into stack and mark it as visited
    stack.append(0)
    visited[0] = True

    # while stack is not empty, do DFS
    while stack:
        # pop the top vertex from stack
        current_vertex = stack.pop()

        # iterate over its neighbors
        for neighbor in range(len(adj_matrix)):
            if adj_matrix[current_vertex][neighbor] == 1 and not visited[neighbor]:
                visited[neighbor] = True
                stack.append(neighbor)

    # check if all vertices have been visited
    return all(visited)


In [25]:
is_connected(adj_matrix=A)

True

In [26]:
def count_connected_components(adj_matrix):
    # initialize visited list and stack
    visited = [False] * len(adj_matrix)
    count = 0

    # for each vertex, run DFS
    for vertex in range(len(adj_matrix)):
        if not visited[vertex]:
            # increment count and perform DFS
            count += 1
            stack = []
            stack.append(vertex)
            visited[vertex] = True

            while stack:
                # pop the top vertex from stack
                current_vertex = stack.pop()

                # iterate over its neighbors
                for neighbor in range(len(adj_matrix)):
                    if adj_matrix[current_vertex][neighbor] == 1 and not visited[neighbor]:
                        visited[neighbor] = True
                        stack.append(neighbor)

    # return the count of connected components
    return count


In [27]:
count_connected_components(adj_matrix=A)

1

In [28]:
def max_degree(adj_matrix):
    # initialize max degree to 0
    max_deg = 0

    # iterate over each row in the adjacency matrix
    for i in range(len(adj_matrix)):
        # count the number of non-zero elements in the row
        row_deg = sum(adj_matrix[i])

        # update the max degree if the current row degree is greater than the current max degree
        if row_deg > max_deg:
            max_deg = row_deg

    # return the max degree
    return max_deg


In [29]:
max_degree(adj_matrix=A)

5

In [30]:
A@(A@(A@(A@A)))

array([[46, 59, 14, 62, 30, 40,  5, 21, 38, 25],
       [59, 36, 28, 88, 57, 28, 10, 14, 30, 27],
       [14, 28,  2, 14,  6, 17,  2, 10, 19, 10],
       [62, 88, 14, 58, 33, 58, 11, 37, 68, 30],
       [30, 57,  6, 33, 24, 32,  9, 20, 47, 32],
       [40, 28, 17, 58, 32, 22,  4, 11, 19, 16],
       [ 5, 10,  2, 11,  9,  4,  2,  2,  9, 13],
       [21, 14, 10, 37, 20, 11,  2,  4,  8, 11],
       [38, 30, 19, 68, 47, 19,  9,  8, 26, 33],
       [25, 27, 10, 30, 32, 16, 13, 11, 33, 20]])

In [34]:
A@(A@A)

array([[ 4,  7,  1,  7,  2,  5,  0,  2,  3,  2],
       [ 7,  2,  4, 10,  7,  2,  1,  1,  2,  2],
       [ 1,  4,  0,  1,  0,  2,  0,  1,  2,  1],
       [ 7, 10,  1,  4,  2,  7,  1,  5,  8,  2],
       [ 2,  7,  0,  2,  2,  3,  1,  2,  6,  5],
       [ 5,  2,  2,  7,  3,  2,  0,  1,  1,  1],
       [ 0,  1,  0,  1,  1,  0,  0,  0,  1,  3],
       [ 2,  1,  1,  5,  2,  1,  0,  0,  0,  1],
       [ 3,  2,  2,  8,  6,  1,  1,  0,  2,  5],
       [ 2,  2,  1,  2,  5,  1,  3,  1,  5,  2]])

In [32]:
run = True
A_l = A
l = 2
while(run):
    A_l = A@A_l
    min_val = np.min(A_l)
    print(f"l: {l} | min: {min_val}")
    if(min_val > 0):
        break
    else:
        l += 1

l: 2 | min: 0
l: 3 | min: 0
l: 4 | min: 1
